### ISSUE TITLE
敵の視認性がとても悪い

### ISSUE THREAD

**Issue by koutya0125** [tedo0627/KZEAddon#3]
##内容
半透明化している味方の後ろからゾンビを見ると、ゾンビが全く見えない
![image](https://user-images.githubusercontent.com/67880565/167291916-59595878-1e5a-4f88-9754-775784ee87cd.png)

##実行環境
windows11 
minecraft1.17.1
forge1.17.1 37.1.1

**Comment by tedo0627** [comment]
可能ならば修正します
これをシングルプレイで、透明のmob越しに他のmobを見たら、見えなかったり、見えたりするよくわからない挙動をしているので直せるかはあまり自信ないです

**Comment by tedo0627** [comment]
直しました
